#pragma once

enum class MoveResult {
    SUCCESS,
    INVALID_MOVE,
    INVALID_FROM_COLUMN,
    INVALID_TO_COLUMN,
    NOT_CURRENT_PLAYER,
    DICE_NOT_ROLLED,
    NO_AVAILABLE_MOVES,
    CANNOT_BEAR_OFF,
    BLOCKED_BY_OPPONENT,
    GAME_NOT_STARTED,
    GAME_ALREADY_OVER
};

